version: "3.7"
services:
  redis:
    image: "redis:alpine"
    command: redis-server /redis.conf
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
      - ./redis.conf:/redis.conf

  proxypool:
    build: .
    ports:
      - "5000:5000"