version: "1.0"
services:
  redis:
    image: "redis:alpine"
    command: redis-server /redis.conf
    volumes:
      - ./data:/data
      - ./redis.conf:/redis.conf

  proxypool:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis